<?php
/**
 * Ebizmarts_Abandonedcart Magento JS component
 *
 * @category    Ebizmarts
 * @package     Ebizmarts_Abandonedcart
 * @author      Ebizmarts Team <info@ebizmarts.com>
 * @copyright   Ebizmarts (http://ebizmarts.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
<h4>
    <img width="224px" height="60px" src="https://ebizmarts-website.s3.amazonaws.com/Logo_Ebizmarts.png"/><br><br>
    <div style="padding-left: 30px;">
        <p><strong style="color:#EA7601;">Ebizmarts Abandoned Cart v<?php echo $this->getVersion()?></strong> <br>Need help? See our <a href="http://wiki.ebizmarts.com/abandoned-carts/" target="_blank">Wiki</a> or browse our <a href="http://ebizmarts.com/forums/view/1" target="_blank">support forums</a> Got feedback? <a href="mailto:mailchimp@ebizmarts-desk.zendesk.com?Subject=Support Abandoned Cart Version <?php echo $this->getVersion() ?>">Email us</a></p>
        <p>You can find more extensions in our <a href="http://store.ebizmarts.com" target="_blank">Store</a></p>
    </div>
    <?php if(!$this->mandrillEnabled()) :?>
        <div class="message-error" style="padding-left: 30px;">
            You must setup Mandrill extension to use this extension
        </div>
    <?php endif; ?>
    <div  style="padding-left: 30px">
        <p>
            <h3><a style="padding-top: 5px;padding-bottom:5px;padding-left: 30px;padding-right: 30px;background-color:#EB5202;color:white;font-weight: bold" href="http://www.mailchimp.com/signup?pid=ebizmarts&source=website" target="_blank">Support MageMonkey, Subscribe for a free MailChimp Account!</a> </h3>
        </p>
    </div>
</h4>
</div>
